### PR TITLE
Add matrices tests, bring alphabets within function local scope

### PR DESCRIPTION
**Pull request by kmayerb**
This pull request contains the following:
1. ` parasail_aa_alphabet` and `parasail_aa_alphabet_with_unknown` are passed as arguments into the local scope of relevant functions in` matrices.py`
2. Docstrings now contain simple examples
3. test_matrices includes some relevant unit tests.

### CODE REVIEW

**Comment by kmayerb** [comment]
numba is a required dependency for the current tests to run. No version yet specified in either requirements file.

**Comment by kmayerb** [comment]
Travis badge is based on the forked repo, and will need to be changed to the master repo associated with AFG's account

**Comment by agartland** [comment]
Are we sure we want to require numba?

**Comment by kmayerb** [comment]
If we don't require it then some tests on travis will fail.  Travis uses the requirements file to build the environment for testing. Is there a good reason to not require it and make tests conditional.  We can do that if you think it prudent

```
pwseqdist/tests/test_distances.py .............FF                        [ 65%]
250pwseqdist/tests/test_matrices.py ........                                [100%]
251
252=================================== FAILURES ===================================
253___________________________ TestNumba.test_nb_pw_sq ____________________________
254
255self = <pwseqdist.tests.test_distances.TestNumba testMethod=test_nb_pw_sq>
256
257    def test_nb_pw_sq(self):
258        subst_dict = pwsd.matrices.dict_from_matrix(parasail.blosum62)
259        dvec = pwsd.apply_pairwise_sq(seqs[:10], pwsd.metrics.str_subst_metric, subst_dict=subst_dict, ncpus=1)
260    
261>       subst_dict = pwsd.numba_tools.nb_dict_from_matrix(parasail.blosum62)
262
263pwseqdist/tests/test_distances.py:183: 
264_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
265
266subst = <parasail.bindings_v2.Matrix object at 0x7f0c88959198>
267
268    def nb_dict_from_matrix(subst):
269        """Converts a parasail substitution matrix into a numba.typed.Dict
270        that can be used with he numba metrics"""
271>       subst_dict = numba.typed.Dict.empty(key_type=numba.types.unicode_type,
272                                   value_type=numba.types.int32)
273E       NameError: name 'numba' is not defined
```

**Comment by kmayerb** [comment]
All tests passed on latest commit. If you accept the PR, you probably want to enable Travis-Tracking of your master branch if not already and then add the BADGE to the README.md:  ```
([Build Status](https://travis-ci.com/agartland/pwseqdist)
```

**Pull request merged**
